### ISSUE TITLE
Bug: show the sun rise in local time

### ISSUE THREAD

**Issue by cinghiopinghio** [woheller69/PeakOrama#2]
Dear, 
This is an amazing app. Thanks for the effort.

I think the sun rise time is in UTG. It would be cool to see it in local time

**Comment by cinghiopinghio** [comment]
Nevertheless, the example embeddings in their readme workers just fine displaying the local time. 
I tried to have a look at your code without success, I'm not expert in java and android apps in general.

**Comment by woheller69** [comment]
Which example are you referring to? I am using their basic canvas example in my code.
https://github.com/woheller69/PeakOrama/blob/master/app/src/main/assets/canvas.html

**Comment by woheller69** [comment]
Fixed it

**Comment by cinghiopinghio** [comment]
Yes, I was checking the [basic example](https://fabiz.github.io/PeakFinder-API/basicexample_canvas.html), but
also the one you linked to works in the browser (on the desktop only though, on mobile both don't load).
