### ISSUE TITLE
App crashes when compass is activated

### ISSUE THREAD

**Issue by rambonette** [woheller69/PeakOrama#3]
Hi,

first of all congrats for the app, looks really promising.

I noticed the app crashes when I switch to "compass-driven" mode.
I'm running android 13. Rom is based on LineageOs with no gms. I can confirm the compass works no problem.

I'm on the go right now so I cannot access crash logs from adb, but I can attach a small screen recording to reproduce the issue (video is cropped on top and bottom for obvious privacy reasons).

I can provide crash logs in the future if you wish.

https://github.com/user-attachments/assets/a75d682b-6e8a-4af6-bd8e-f96bb49737af

**Comment by woheller69** [comment]
Should be fixed already in V3.1

**Comment by rambonette** [comment]
Never mind, I'm using the 3.0 version from fdroid. I'll wait for the 3.1 to release on fdroid then.
Cheers
