### ISSUE TITLE
Imperial Units

### ISSUE THREAD

**Issue by Joeviocoe** [woheller69/PeakOrama#4]
Humble ask from the backwards lands of merica.  
Can we get feet for altitude and miles for distance and visibility range, instead of meters and kilometers.
A persistent settings toggle is preferred, but if creating a new UI is a lot of work, then a locality check for places that use imperial could be sufficient.

Thank you.

**Comment by woheller69** [comment]
already implemented. Coming in V3.2

**Comment by Joeviocoe** [comment]
Works great, thank you.
