### ISSUE TITLE
Map is turned by 180º

### ISSUE THREAD

**Issue by bege10** [woheller69/PeakOrama#5]
With activated compass I don't see the hills in front of me. When I turn round I see them in the app.
Map and compass apps show the correct direction, so the compass is calibrated.
The direction displayed in the app is correct, the sun position is correct but the map shows the landscape of the opposite direction.
Currently the sun is SW and with activated compass below I see the hills NE of here.

Shiftphone 6mq, /e/OS (based on LineageOS for microG), Android 13

**Comment by woheller69** [comment]
Strange. Does THIS compass app work for you?

https://github.com/Kr0oked/Compass

I am using their algorithms. There are several possible APIs for compass, maybe there is something wrong on your phone.
Where are you located? In Germany?

**Comment by woheller69** [comment]
please add steps how to reproduce.
If you are using the search button instead of your current location please note that this will be the viewpoint and direction will differ from current location

**Comment by bege10** [comment]
Today it works correct. I cannot reproduce the issue any more.
